flask/app/models.py
from . import db 

class Usuario(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    nombre = db.Column(db.String(50), nullable=False)
    email = db.Column(db.String(120), unique=True, nullable=False)
   

flask/app/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from .config import Config
from flask_migrate import Migrate

db = SQLAlchemy()


def crear_app():
    app = Flask(__name__)
    app.config.from_object(Config)
  
    db.init_app(app)
    migrate = Migrate (app, db)
  
    from .routes.usuarios import usuarios_bp
    app.register_blueprint(usuarios_bp)
  
    return app

flask/app/routes/usuarios.py
from flask import Blueprint, render_template, request, redirect,url_for
from app import db
from app.models import Usuario

usuarios_bp = Blueprint('usuarios', __name__,url_prefix='/usuarios')

@usuarios_bp.route('/')
def lista():
   usuarios = Usuario.query.all()
   return render_template('usuarios/lista.html', usuarios=usuarios)

@usuarios_bp.route('/crear', methods=['GET', 'POST'])
def crear():
   if request.method == 'POST':
      nombre = request.form['nombre']
      email = request.form['email']
      nuevo = Usuario(nombre=nombre, email=email)
      db.session.add(nuevo)
      db.session.commit()
      return redirect(url_for('usuarios.lista'))
   return render_template('usuarios/formulario.html')

@usuarios_bp.route('/eliminar/<int:id>')
def eliminar(id):    
    usuario = Usuario.query.get_or_404(id)
    db.session.delete(usuario)
    db.session.commit()
    return redirect(url_for('usuarios.lista'))

flask/app/templates/usuarios/formulario.html
<h1>Crear Usuario</h1>
<form method="post">
    Nombre: <input type="text" name="nombre"><br>
    Email: <input type="email" name="email"><br>
    <input type="submit" value="Guardar">
</form>

flask/app/templates/usuarios/lista.html
<h1>Lista de Usuarios</h1>
<a href="{{ url_for('usuarios.crear') }}">Nuevo Usuario</a>
<ul>
    {% for u in usuarios %}
    <li>{{ u.nombre }} - {{ u.email }}
        <a href="{{ url_for('usuarios.eliminar', id=u.id)

}}">[Eliminar]</a>
    </li>
    {% endfor %}
</ul>